//go:build !ignore_autogenerated

/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceQuota) DeepCopyInto(out *NamespaceQuota) {
	*out = *in
	if in.MaxVolumes != nil {
		in, out := &in.MaxVolumes, &out.MaxVolumes
		*out = new(int32)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = make(map[string]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceQuota.
func (in *NamespaceQuota) DeepCopy() *NamespaceQuota {
	if in == nil {
		return nil
	}
	out := new(NamespaceQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamespaceUsage) DeepCopyInto(out *NamespaceUsage) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(map[string]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamespaceUsage.
func (in *NamespaceUsage) DeepCopy() *NamespaceUsage {
	if in == nil {
		return nil
	}
	out := new(NamespaceUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParameterPolicy) DeepCopyInto(out *ParameterPolicy) {
	*out = *in
	if in.Allowed != nil {
		in, out := &in.Allowed, &out.Allowed
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Forced != nil {
		in, out := &in.Forced, &out.Forced
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxInt != nil {
		in, out := &in.MaxInt, &out.MaxInt
		*out = make(map[string]int64, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MaxVolumeBytes != nil {
		in, out := &in.MaxVolumeBytes, &out.MaxVolumeBytes
		x := (*in).DeepCopy()
		*out = &x
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParameterPolicy.
func (in *ParameterPolicy) DeepCopy() *ParameterPolicy {
	if in == nil {
		return nil
	}
	out := new(ParameterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxStorage) DeepCopyInto(out *ProxmoxStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxStorage.
func (in *ProxmoxStorage) DeepCopy() *ProxmoxStorage {
	if in == nil {
		return nil
	}
	out := new(ProxmoxStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxStorageList) DeepCopyInto(out *ProxmoxStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxStorageList.
func (in *ProxmoxStorageList) DeepCopy() *ProxmoxStorageList {
	if in == nil {
		return nil
	}
	out := new(ProxmoxStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxStorageSpec) DeepCopyInto(out *ProxmoxStorageSpec) {
	*out = *in
	if in.Types != nil {
		in, out := &in.Types, &out.Types
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxStorageSpec.
func (in *ProxmoxStorageSpec) DeepCopy() *ProxmoxStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ProxmoxStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxStorageStatus) DeepCopyInto(out *ProxmoxStorageStatus) {
	*out = *in
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxStorageStatus.
func (in *ProxmoxStorageStatus) DeepCopy() *ProxmoxStorageStatus {
	if in == nil {
		return nil
	}
	out := new(ProxmoxStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolume) DeepCopyInto(out *ProxmoxVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolume.
func (in *ProxmoxVolume) DeepCopy() *ProxmoxVolume {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeAttachment) DeepCopyInto(out *ProxmoxVolumeAttachment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeAttachment.
func (in *ProxmoxVolumeAttachment) DeepCopy() *ProxmoxVolumeAttachment {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeAttachment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxVolumeAttachment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeAttachmentList) DeepCopyInto(out *ProxmoxVolumeAttachmentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxVolumeAttachment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeAttachmentList.
func (in *ProxmoxVolumeAttachmentList) DeepCopy() *ProxmoxVolumeAttachmentList {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeAttachmentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxVolumeAttachmentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeAttachmentSpec) DeepCopyInto(out *ProxmoxVolumeAttachmentSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeAttachmentSpec.
func (in *ProxmoxVolumeAttachmentSpec) DeepCopy() *ProxmoxVolumeAttachmentSpec {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeAttachmentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeAttachmentStatus) DeepCopyInto(out *ProxmoxVolumeAttachmentStatus) {
	*out = *in
	if in.AttachedAt != nil {
		in, out := &in.AttachedAt, &out.AttachedAt
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeAttachmentStatus.
func (in *ProxmoxVolumeAttachmentStatus) DeepCopy() *ProxmoxVolumeAttachmentStatus {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeAttachmentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeList) DeepCopyInto(out *ProxmoxVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeList.
func (in *ProxmoxVolumeList) DeepCopy() *ProxmoxVolumeList {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeSnapshot) DeepCopyInto(out *ProxmoxVolumeSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeSnapshot.
func (in *ProxmoxVolumeSnapshot) DeepCopy() *ProxmoxVolumeSnapshot {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxVolumeSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeSnapshotList) DeepCopyInto(out *ProxmoxVolumeSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ProxmoxVolumeSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeSnapshotList.
func (in *ProxmoxVolumeSnapshotList) DeepCopy() *ProxmoxVolumeSnapshotList {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ProxmoxVolumeSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeSnapshotSpec) DeepCopyInto(out *ProxmoxVolumeSnapshotSpec) {
	*out = *in
	out.ClaimRef = in.ClaimRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeSnapshotSpec.
func (in *ProxmoxVolumeSnapshotSpec) DeepCopy() *ProxmoxVolumeSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeSnapshotStatus) DeepCopyInto(out *ProxmoxVolumeSnapshotStatus) {
	*out = *in
	if in.CreationTime != nil {
		in, out := &in.CreationTime, &out.CreationTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeSnapshotStatus.
func (in *ProxmoxVolumeSnapshotStatus) DeepCopy() *ProxmoxVolumeSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeSpec) DeepCopyInto(out *ProxmoxVolumeSpec) {
	*out = *in
	if in.Parameters != nil {
		in, out := &in.Parameters, &out.Parameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Source != nil {
		in, out := &in.Source, &out.Source
		*out = new(VolumeSource)
		**out = **in
	}
	if in.MutableParameters != nil {
		in, out := &in.MutableParameters, &out.MutableParameters
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	out.ClaimRef = in.ClaimRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeSpec.
func (in *ProxmoxVolumeSpec) DeepCopy() *ProxmoxVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProxmoxVolumeStatus) DeepCopyInto(out *ProxmoxVolumeStatus) {
	*out = *in
	if in.AccessibleTopology != nil {
		in, out := &in.AccessibleTopology, &out.AccessibleTopology
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LastSyncTime != nil {
		in, out := &in.LastSyncTime, &out.LastSyncTime
		*out = (*in).DeepCopy()
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProxmoxVolumeStatus.
func (in *ProxmoxVolumeStatus) DeepCopy() *ProxmoxVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(ProxmoxVolumeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QuotaUsage) DeepCopyInto(out *QuotaUsage) {
	*out = *in
	if in.Capacity != nil {
		in, out := &in.Capacity, &out.Capacity
		*out = make(map[string]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QuotaUsage.
func (in *QuotaUsage) DeepCopy() *QuotaUsage {
	if in == nil {
		return nil
	}
	out := new(QuotaUsage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantClaimRef) DeepCopyInto(out *TenantClaimRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantClaimRef.
func (in *TenantClaimRef) DeepCopy() *TenantClaimRef {
	if in == nil {
		return nil
	}
	out := new(TenantClaimRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantCluster) DeepCopyInto(out *TenantCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantCluster.
func (in *TenantCluster) DeepCopy() *TenantCluster {
	if in == nil {
		return nil
	}
	out := new(TenantCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantClusterList) DeepCopyInto(out *TenantClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TenantCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantClusterList.
func (in *TenantClusterList) DeepCopy() *TenantClusterList {
	if in == nil {
		return nil
	}
	out := new(TenantClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TenantClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantClusterSpec) DeepCopyInto(out *TenantClusterSpec) {
	*out = *in
	if in.VMIDs != nil {
		in, out := &in.VMIDs, &out.VMIDs
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.LegacyControllerVMIDs != nil {
		in, out := &in.LegacyControllerVMIDs, &out.LegacyControllerVMIDs
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.AllowedStorages != nil {
		in, out := &in.AllowedStorages, &out.AllowedStorages
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.ParameterPolicy != nil {
		in, out := &in.ParameterPolicy, &out.ParameterPolicy
		*out = new(ParameterPolicy)
		(*in).DeepCopyInto(*out)
	}
	if in.Quota != nil {
		in, out := &in.Quota, &out.Quota
		*out = new(TenantQuota)
		(*in).DeepCopyInto(*out)
	}
	if in.NamespaceQuotas != nil {
		in, out := &in.NamespaceQuotas, &out.NamespaceQuotas
		*out = make([]NamespaceQuota, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantClusterSpec.
func (in *TenantClusterSpec) DeepCopy() *TenantClusterSpec {
	if in == nil {
		return nil
	}
	out := new(TenantClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantClusterStatus) DeepCopyInto(out *TenantClusterStatus) {
	*out = *in
	if in.ResolvedVMIDs != nil {
		in, out := &in.ResolvedVMIDs, &out.ResolvedVMIDs
		*out = make([]int32, len(*in))
		copy(*out, *in)
	}
	if in.VMIDsObservedAt != nil {
		in, out := &in.VMIDsObservedAt, &out.VMIDsObservedAt
		*out = (*in).DeepCopy()
	}
	in.Used.DeepCopyInto(&out.Used)
	if in.NamespaceUsed != nil {
		in, out := &in.NamespaceUsed, &out.NamespaceUsed
		*out = make([]NamespaceUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantClusterStatus.
func (in *TenantClusterStatus) DeepCopy() *TenantClusterStatus {
	if in == nil {
		return nil
	}
	out := new(TenantClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TenantQuota) DeepCopyInto(out *TenantQuota) {
	*out = *in
	if in.MaxVolumes != nil {
		in, out := &in.MaxVolumes, &out.MaxVolumes
		*out = new(int32)
		**out = **in
	}
	if in.MaxCapacity != nil {
		in, out := &in.MaxCapacity, &out.MaxCapacity
		*out = make(map[string]resource.Quantity, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TenantQuota.
func (in *TenantQuota) DeepCopy() *TenantQuota {
	if in == nil {
		return nil
	}
	out := new(TenantQuota)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VolumeSource) DeepCopyInto(out *VolumeSource) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VolumeSource.
func (in *VolumeSource) DeepCopy() *VolumeSource {
	if in == nil {
		return nil
	}
	out := new(VolumeSource)
	in.DeepCopyInto(out)
	return out
}
