// Copyright 2023 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The volume API served by the operator binary (ADR 6).
//
// Every request is authenticated by a Keycloak bearer token whose azp resolves
// to exactly one TenantCluster and therefore one namespace. No field in this
// proto carries a namespace, tenant identity or owner: those are derived from
// the bearer token by the server and never accepted from the wire. This is the
// reason a compromised tenant cannot name another tenant's namespace, and it is
// load-bearing -- see volume-control-plane.md, "Authorization: four layers".

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: volume/v1/volume.proto

package volumev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ClaimRef identifies the PVC in the tenant cluster this volume was
// provisioned for. Populated from csi.storage.k8s.io/pvc/{name,namespace}
// when csi-provisioner is started with --extra-create-metadata.
//
// Tenant-asserted: see volume-control-plane.md, "Quotas: three layers".
type ClaimRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimRef) Reset() {
	*x = ClaimRef{}
	mi := &file_volume_v1_volume_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimRef) ProtoMessage() {}

func (x *ClaimRef) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimRef.ProtoReflect.Descriptor instead.
func (*ClaimRef) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{0}
}

func (x *ClaimRef) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ClaimRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// VolumeSource references content to populate a new volume from.
// At most one field may be set.
type VolumeSource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of a ProxmoxVolume in the tenant's namespace.
	VolumeName string `protobuf:"bytes,1,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
	// Name of a ProxmoxVolumeSnapshot in the tenant's namespace.
	SnapshotName  string `protobuf:"bytes,2,opt,name=snapshot_name,json=snapshotName,proto3" json:"snapshot_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeSource) Reset() {
	*x = VolumeSource{}
	mi := &file_volume_v1_volume_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeSource) ProtoMessage() {}

func (x *VolumeSource) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeSource.ProtoReflect.Descriptor instead.
func (*VolumeSource) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{1}
}

func (x *VolumeSource) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

func (x *VolumeSource) GetSnapshotName() string {
	if x != nil {
		return x.SnapshotName
	}
	return ""
}

// TopologyRequirement carries the zones (Proxmox nodes) the volume must be
// accessible from.
type TopologyRequirement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Zones         []string               `protobuf:"bytes,1,rep,name=zones,proto3" json:"zones,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopologyRequirement) Reset() {
	*x = TopologyRequirement{}
	mi := &file_volume_v1_volume_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyRequirement) ProtoMessage() {}

func (x *TopologyRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyRequirement.ProtoReflect.Descriptor instead.
func (*TopologyRequirement) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{2}
}

func (x *TopologyRequirement) GetZones() []string {
	if x != nil {
		return x.Zones
	}
	return nil
}

type CreateVolumeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the PersistentVolume name (pvc-<uuid>), which is also the
	// ProxmoxVolume's name and what makes provisioning idempotent.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// pv_name is carried for readability; it equals name today.
	PvName string `protobuf:"bytes,2,opt,name=pv_name,json=pvName,proto3" json:"pv_name,omitempty"`
	// claim_ref is the tenant-side PVC this was provisioned for.
	ClaimRef      *ClaimRef `protobuf:"bytes,3,opt,name=claim_ref,json=claimRef,proto3" json:"claim_ref,omitempty"`
	Region        string    `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Zone          string    `protobuf:"bytes,5,opt,name=zone,proto3" json:"zone,omitempty"`
	Storage       string    `protobuf:"bytes,6,opt,name=storage,proto3" json:"storage,omitempty"`
	CapacityBytes int64     `protobuf:"varint,7,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	// parameters are the StorageClass parameters, filtered by the tenant's
	// ParameterPolicy.
	Parameters map[string]string `protobuf:"bytes,8,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// mutable_parameters are the VolumeAttributesClass parameters, kept
	// separate from creation parameters.
	MutableParameters map[string]string `protobuf:"bytes,9,rep,name=mutable_parameters,json=mutableParameters,proto3" json:"mutable_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// source clones an existing volume or restores from a snapshot.
	Source *VolumeSource `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	// topology_requirement restricts the volume to the given zones.
	TopologyRequirement *TopologyRequirement `protobuf:"bytes,11,opt,name=topology_requirement,json=topologyRequirement,proto3" json:"topology_requirement,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreateVolumeRequest) Reset() {
	*x = CreateVolumeRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeRequest) ProtoMessage() {}

func (x *CreateVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeRequest.ProtoReflect.Descriptor instead.
func (*CreateVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVolumeRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVolumeRequest) GetPvName() string {
	if x != nil {
		return x.PvName
	}
	return ""
}

func (x *CreateVolumeRequest) GetClaimRef() *ClaimRef {
	if x != nil {
		return x.ClaimRef
	}
	return nil
}

func (x *CreateVolumeRequest) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *CreateVolumeRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *CreateVolumeRequest) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *CreateVolumeRequest) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *CreateVolumeRequest) GetParameters() map[string]string {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *CreateVolumeRequest) GetMutableParameters() map[string]string {
	if x != nil {
		return x.MutableParameters
	}
	return nil
}

func (x *CreateVolumeRequest) GetSource() *VolumeSource {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *CreateVolumeRequest) GetTopologyRequirement() *TopologyRequirement {
	if x != nil {
		return x.TopologyRequirement
	}
	return nil
}

type CreateVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	CapacityBytes int64                  `protobuf:"varint,2,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	// accessible_topology lists the zones the volume is reachable from.
	AccessibleTopology []string `protobuf:"bytes,3,rep,name=accessible_topology,json=accessibleTopology,proto3" json:"accessible_topology,omitempty"`
	// volume_context is the CSI VolumeContext the tenant's PV carries, exactly
	// as direct mode's CreateVolume builds it. The node plugin reads mount-time
	// settings from it (rootDirPermissions, filesystem options).
	VolumeContext map[string]string `protobuf:"bytes,4,rep,name=volume_context,json=volumeContext,proto3" json:"volume_context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVolumeResponse) Reset() {
	*x = CreateVolumeResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVolumeResponse) ProtoMessage() {}

func (x *CreateVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVolumeResponse.ProtoReflect.Descriptor instead.
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVolumeResponse) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *CreateVolumeResponse) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *CreateVolumeResponse) GetAccessibleTopology() []string {
	if x != nil {
		return x.AccessibleTopology
	}
	return nil
}

func (x *CreateVolumeResponse) GetVolumeContext() map[string]string {
	if x != nil {
		return x.VolumeContext
	}
	return nil
}

type DeleteVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeRequest) Reset() {
	*x = DeleteVolumeRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeRequest) ProtoMessage() {}

func (x *DeleteVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeRequest.ProtoReflect.Descriptor instead.
func (*DeleteVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

type DeleteVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVolumeResponse) Reset() {
	*x = DeleteVolumeResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVolumeResponse) ProtoMessage() {}

func (x *DeleteVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVolumeResponse.ProtoReflect.Descriptor instead.
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{6}
}

type ExpandVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	CapacityBytes int64                  `protobuf:"varint,2,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExpandVolumeRequest) Reset() {
	*x = ExpandVolumeRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandVolumeRequest) ProtoMessage() {}

func (x *ExpandVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandVolumeRequest.ProtoReflect.Descriptor instead.
func (*ExpandVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{7}
}

func (x *ExpandVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ExpandVolumeRequest) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

type ExpandVolumeResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CapacityBytes         int64                  `protobuf:"varint,1,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	NodeExpansionRequired bool                   `protobuf:"varint,2,opt,name=node_expansion_required,json=nodeExpansionRequired,proto3" json:"node_expansion_required,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ExpandVolumeResponse) Reset() {
	*x = ExpandVolumeResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExpandVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpandVolumeResponse) ProtoMessage() {}

func (x *ExpandVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpandVolumeResponse.ProtoReflect.Descriptor instead.
func (*ExpandVolumeResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{8}
}

func (x *ExpandVolumeResponse) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *ExpandVolumeResponse) GetNodeExpansionRequired() bool {
	if x != nil {
		return x.NodeExpansionRequired
	}
	return false
}

type ModifyVolumeRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	VolumeId          string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	MutableParameters map[string]string      `protobuf:"bytes,2,rep,name=mutable_parameters,json=mutableParameters,proto3" json:"mutable_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ModifyVolumeRequest) Reset() {
	*x = ModifyVolumeRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyVolumeRequest) ProtoMessage() {}

func (x *ModifyVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyVolumeRequest.ProtoReflect.Descriptor instead.
func (*ModifyVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{9}
}

func (x *ModifyVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *ModifyVolumeRequest) GetMutableParameters() map[string]string {
	if x != nil {
		return x.MutableParameters
	}
	return nil
}

type ModifyVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifyVolumeResponse) Reset() {
	*x = ModifyVolumeResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifyVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyVolumeResponse) ProtoMessage() {}

func (x *ModifyVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyVolumeResponse.ProtoReflect.Descriptor instead.
func (*ModifyVolumeResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{10}
}

type AttachVolumeRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	VolumeId string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	NodeId   string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Vmid     int32                  `protobuf:"varint,3,opt,name=vmid,proto3" json:"vmid,omitempty"`
	Readonly bool                   `protobuf:"varint,4,opt,name=readonly,proto3" json:"readonly,omitempty"`
	// mutable_parameters lets the tenant apply a VolumeAttributesClass at
	// attach time, which is the only moment the throttle can be written for a
	// volume that was detached when the class was assigned.
	MutableParameters map[string]string `protobuf:"bytes,5,rep,name=mutable_parameters,json=mutableParameters,proto3" json:"mutable_parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AttachVolumeRequest) Reset() {
	*x = AttachVolumeRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachVolumeRequest) ProtoMessage() {}

func (x *AttachVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachVolumeRequest.ProtoReflect.Descriptor instead.
func (*AttachVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{11}
}

func (x *AttachVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *AttachVolumeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AttachVolumeRequest) GetVmid() int32 {
	if x != nil {
		return x.Vmid
	}
	return 0
}

func (x *AttachVolumeRequest) GetReadonly() bool {
	if x != nil {
		return x.Readonly
	}
	return false
}

func (x *AttachVolumeRequest) GetMutableParameters() map[string]string {
	if x != nil {
		return x.MutableParameters
	}
	return nil
}

type AttachVolumeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// device_path is the stable /dev/disk/by-id/wwn-0x... link.
	DevicePath string `protobuf:"bytes,1,opt,name=device_path,json=devicePath,proto3" json:"device_path,omitempty"`
	// lun is the SCSI index the disk was attached at.
	Lun int32 `protobuf:"varint,2,opt,name=lun,proto3" json:"lun,omitempty"`
	// resize_required tells the node plugin to grow the filesystem after mount.
	ResizeRequired bool `protobuf:"varint,3,opt,name=resize_required,json=resizeRequired,proto3" json:"resize_required,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AttachVolumeResponse) Reset() {
	*x = AttachVolumeResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttachVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttachVolumeResponse) ProtoMessage() {}

func (x *AttachVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttachVolumeResponse.ProtoReflect.Descriptor instead.
func (*AttachVolumeResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{12}
}

func (x *AttachVolumeResponse) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *AttachVolumeResponse) GetLun() int32 {
	if x != nil {
		return x.Lun
	}
	return 0
}

func (x *AttachVolumeResponse) GetResizeRequired() bool {
	if x != nil {
		return x.ResizeRequired
	}
	return false
}

type DetachVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VolumeId      string                 `protobuf:"bytes,1,opt,name=volume_id,json=volumeId,proto3" json:"volume_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Vmid          int32                  `protobuf:"varint,3,opt,name=vmid,proto3" json:"vmid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachVolumeRequest) Reset() {
	*x = DetachVolumeRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachVolumeRequest) ProtoMessage() {}

func (x *DetachVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachVolumeRequest.ProtoReflect.Descriptor instead.
func (*DetachVolumeRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{13}
}

func (x *DetachVolumeRequest) GetVolumeId() string {
	if x != nil {
		return x.VolumeId
	}
	return ""
}

func (x *DetachVolumeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *DetachVolumeRequest) GetVmid() int32 {
	if x != nil {
		return x.Vmid
	}
	return 0
}

type DetachVolumeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DetachVolumeResponse) Reset() {
	*x = DetachVolumeResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetachVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetachVolumeResponse) ProtoMessage() {}

func (x *DetachVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DetachVolumeResponse.ProtoReflect.Descriptor instead.
func (*DetachVolumeResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{14}
}

type CreateSnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the VolumeSnapshot name, used to name the snapshot disk.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// source_volume_name is a ProxmoxVolume in the tenant's namespace.
	SourceVolumeName string `protobuf:"bytes,2,opt,name=source_volume_name,json=sourceVolumeName,proto3" json:"source_volume_name,omitempty"`
	// zone overrides the snapshot's destination node when the storage is
	// available on multiple nodes.
	Zone          string `protobuf:"bytes,3,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{15}
}

func (x *CreateSnapshotRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSnapshotRequest) GetSourceVolumeName() string {
	if x != nil {
		return x.SourceVolumeName
	}
	return ""
}

func (x *CreateSnapshotRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type CreateSnapshotResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId       string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	ReadyToUse       bool                   `protobuf:"varint,2,opt,name=ready_to_use,json=readyToUse,proto3" json:"ready_to_use,omitempty"`
	RestoreSizeBytes int64                  `protobuf:"varint,3,opt,name=restore_size_bytes,json=restoreSizeBytes,proto3" json:"restore_size_bytes,omitempty"`
	CreationTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateSnapshotResponse) Reset() {
	*x = CreateSnapshotResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotResponse) ProtoMessage() {}

func (x *CreateSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotResponse.ProtoReflect.Descriptor instead.
func (*CreateSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{16}
}

func (x *CreateSnapshotResponse) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *CreateSnapshotResponse) GetReadyToUse() bool {
	if x != nil {
		return x.ReadyToUse
	}
	return false
}

func (x *CreateSnapshotResponse) GetRestoreSizeBytes() int64 {
	if x != nil {
		return x.RestoreSizeBytes
	}
	return 0
}

func (x *CreateSnapshotResponse) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

type DeleteSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId    string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotRequest) Reset() {
	*x = DeleteSnapshotRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotRequest) ProtoMessage() {}

func (x *DeleteSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotRequest.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{17}
}

func (x *DeleteSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type DeleteSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSnapshotResponse) Reset() {
	*x = DeleteSnapshotResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSnapshotResponse) ProtoMessage() {}

func (x *DeleteSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSnapshotResponse.ProtoReflect.Descriptor instead.
func (*DeleteSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{18}
}

type ListSnapshotsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// source_volume_name filters to snapshots of one volume.
	SourceVolumeName string `protobuf:"bytes,1,opt,name=source_volume_name,json=sourceVolumeName,proto3" json:"source_volume_name,omitempty"`
	// snapshot_id filters to one specific snapshot.
	SnapshotId    string `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	MaxEntries    int32  `protobuf:"varint,3,opt,name=max_entries,json=maxEntries,proto3" json:"max_entries,omitempty"`
	StartingToken string `protobuf:"bytes,4,opt,name=starting_token,json=startingToken,proto3" json:"starting_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsRequest) Reset() {
	*x = ListSnapshotsRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsRequest) ProtoMessage() {}

func (x *ListSnapshotsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsRequest.ProtoReflect.Descriptor instead.
func (*ListSnapshotsRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{19}
}

func (x *ListSnapshotsRequest) GetSourceVolumeName() string {
	if x != nil {
		return x.SourceVolumeName
	}
	return ""
}

func (x *ListSnapshotsRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ListSnapshotsRequest) GetMaxEntries() int32 {
	if x != nil {
		return x.MaxEntries
	}
	return 0
}

func (x *ListSnapshotsRequest) GetStartingToken() string {
	if x != nil {
		return x.StartingToken
	}
	return ""
}

type ListSnapshotsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Entries       []*ListSnapshotsResponse_Entry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	NextToken     string                         `protobuf:"bytes,2,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSnapshotsResponse) Reset() {
	*x = ListSnapshotsResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse) ProtoMessage() {}

func (x *ListSnapshotsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{20}
}

func (x *ListSnapshotsResponse) GetEntries() []*ListSnapshotsResponse_Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListSnapshotsResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

type WatchCapacityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// storage filters to one storage name. Empty watches all allowed storages.
	Storage string `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	// zone filters to one Proxmox node. Empty watches all zones.
	Zone          string `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchCapacityRequest) Reset() {
	*x = WatchCapacityRequest{}
	mi := &file_volume_v1_volume_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCapacityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCapacityRequest) ProtoMessage() {}

func (x *WatchCapacityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCapacityRequest.ProtoReflect.Descriptor instead.
func (*WatchCapacityRequest) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{21}
}

func (x *WatchCapacityRequest) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *WatchCapacityRequest) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

type WatchCapacityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Storage        string                 `protobuf:"bytes,1,opt,name=storage,proto3" json:"storage,omitempty"`
	Zone           string                 `protobuf:"bytes,2,opt,name=zone,proto3" json:"zone,omitempty"`
	AvailableBytes int64                  `protobuf:"varint,3,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	TotalBytes     int64                  `protobuf:"varint,4,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	Shared         bool                   `protobuf:"varint,5,opt,name=shared,proto3" json:"shared,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WatchCapacityResponse) Reset() {
	*x = WatchCapacityResponse{}
	mi := &file_volume_v1_volume_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchCapacityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchCapacityResponse) ProtoMessage() {}

func (x *WatchCapacityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchCapacityResponse.ProtoReflect.Descriptor instead.
func (*WatchCapacityResponse) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{22}
}

func (x *WatchCapacityResponse) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *WatchCapacityResponse) GetZone() string {
	if x != nil {
		return x.Zone
	}
	return ""
}

func (x *WatchCapacityResponse) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *WatchCapacityResponse) GetTotalBytes() int64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

func (x *WatchCapacityResponse) GetShared() bool {
	if x != nil {
		return x.Shared
	}
	return false
}

type ListSnapshotsResponse_Entry struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SnapshotId       string                 `protobuf:"bytes,1,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	SourceVolumeId   string                 `protobuf:"bytes,2,opt,name=source_volume_id,json=sourceVolumeId,proto3" json:"source_volume_id,omitempty"`
	ReadyToUse       bool                   `protobuf:"varint,3,opt,name=ready_to_use,json=readyToUse,proto3" json:"ready_to_use,omitempty"`
	RestoreSizeBytes int64                  `protobuf:"varint,4,opt,name=restore_size_bytes,json=restoreSizeBytes,proto3" json:"restore_size_bytes,omitempty"`
	CreationTime     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ListSnapshotsResponse_Entry) Reset() {
	*x = ListSnapshotsResponse_Entry{}
	mi := &file_volume_v1_volume_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSnapshotsResponse_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSnapshotsResponse_Entry) ProtoMessage() {}

func (x *ListSnapshotsResponse_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_volume_v1_volume_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSnapshotsResponse_Entry.ProtoReflect.Descriptor instead.
func (*ListSnapshotsResponse_Entry) Descriptor() ([]byte, []int) {
	return file_volume_v1_volume_proto_rawDescGZIP(), []int{20, 0}
}

func (x *ListSnapshotsResponse_Entry) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

func (x *ListSnapshotsResponse_Entry) GetSourceVolumeId() string {
	if x != nil {
		return x.SourceVolumeId
	}
	return ""
}

func (x *ListSnapshotsResponse_Entry) GetReadyToUse() bool {
	if x != nil {
		return x.ReadyToUse
	}
	return false
}

func (x *ListSnapshotsResponse_Entry) GetRestoreSizeBytes() int64 {
	if x != nil {
		return x.RestoreSizeBytes
	}
	return 0
}

func (x *ListSnapshotsResponse_Entry) GetCreationTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTime
	}
	return nil
}

var File_volume_v1_volume_proto protoreflect.FileDescriptor

const file_volume_v1_volume_proto_rawDesc = "" +
	"\n" +
	"\x16volume/v1/volume.proto\x12\x15proxmox.csi.volume.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"<\n" +
	"\bClaimRef\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"T\n" +
	"\fVolumeSource\x12\x1f\n" +
	"\vvolume_name\x18\x01 \x01(\tR\n" +
	"volumeName\x12#\n" +
	"\rsnapshot_name\x18\x02 \x01(\tR\fsnapshotName\"+\n" +
	"\x13TopologyRequirement\x12\x14\n" +
	"\x05zones\x18\x01 \x03(\tR\x05zones\"\xdc\x05\n" +
	"\x13CreateVolumeRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x17\n" +
	"\apv_name\x18\x02 \x01(\tR\x06pvName\x12<\n" +
	"\tclaim_ref\x18\x03 \x01(\v2\x1f.proxmox.csi.volume.v1.ClaimRefR\bclaimRef\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x12\n" +
	"\x04zone\x18\x05 \x01(\tR\x04zone\x12\x18\n" +
	"\astorage\x18\x06 \x01(\tR\astorage\x12%\n" +
	"\x0ecapacity_bytes\x18\a \x01(\x03R\rcapacityBytes\x12Z\n" +
	"\n" +
	"parameters\x18\b \x03(\v2:.proxmox.csi.volume.v1.CreateVolumeRequest.ParametersEntryR\n" +
	"parameters\x12p\n" +
	"\x12mutable_parameters\x18\t \x03(\v2A.proxmox.csi.volume.v1.CreateVolumeRequest.MutableParametersEntryR\x11mutableParameters\x12;\n" +
	"\x06source\x18\n" +
	" \x01(\v2#.proxmox.csi.volume.v1.VolumeSourceR\x06source\x12]\n" +
	"\x14topology_requirement\x18\v \x01(\v2*.proxmox.csi.volume.v1.TopologyRequirementR\x13topologyRequirement\x1a=\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aD\n" +
	"\x16MutableParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x02\n" +
	"\x14CreateVolumeResponse\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12%\n" +
	"\x0ecapacity_bytes\x18\x02 \x01(\x03R\rcapacityBytes\x12/\n" +
	"\x13accessible_topology\x18\x03 \x03(\tR\x12accessibleTopology\x12e\n" +
	"\x0evolume_context\x18\x04 \x03(\v2>.proxmox.csi.volume.v1.CreateVolumeResponse.VolumeContextEntryR\rvolumeContext\x1a@\n" +
	"\x12VolumeContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"2\n" +
	"\x13DeleteVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\"\x16\n" +
	"\x14DeleteVolumeResponse\"Y\n" +
	"\x13ExpandVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12%\n" +
	"\x0ecapacity_bytes\x18\x02 \x01(\x03R\rcapacityBytes\"u\n" +
	"\x14ExpandVolumeResponse\x12%\n" +
	"\x0ecapacity_bytes\x18\x01 \x01(\x03R\rcapacityBytes\x126\n" +
	"\x17node_expansion_required\x18\x02 \x01(\bR\x15nodeExpansionRequired\"\xea\x01\n" +
	"\x13ModifyVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12p\n" +
	"\x12mutable_parameters\x18\x02 \x03(\v2A.proxmox.csi.volume.v1.ModifyVolumeRequest.MutableParametersEntryR\x11mutableParameters\x1aD\n" +
	"\x16MutableParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x16\n" +
	"\x14ModifyVolumeResponse\"\xb3\x02\n" +
	"\x13AttachVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04vmid\x18\x03 \x01(\x05R\x04vmid\x12\x1a\n" +
	"\breadonly\x18\x04 \x01(\bR\breadonly\x12p\n" +
	"\x12mutable_parameters\x18\x05 \x03(\v2A.proxmox.csi.volume.v1.AttachVolumeRequest.MutableParametersEntryR\x11mutableParameters\x1aD\n" +
	"\x16MutableParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"r\n" +
	"\x14AttachVolumeResponse\x12\x1f\n" +
	"\vdevice_path\x18\x01 \x01(\tR\n" +
	"devicePath\x12\x10\n" +
	"\x03lun\x18\x02 \x01(\x05R\x03lun\x12'\n" +
	"\x0fresize_required\x18\x03 \x01(\bR\x0eresizeRequired\"_\n" +
	"\x13DetachVolumeRequest\x12\x1b\n" +
	"\tvolume_id\x18\x01 \x01(\tR\bvolumeId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12\x12\n" +
	"\x04vmid\x18\x03 \x01(\x05R\x04vmid\"\x16\n" +
	"\x14DetachVolumeResponse\"m\n" +
	"\x15CreateSnapshotRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12,\n" +
	"\x12source_volume_name\x18\x02 \x01(\tR\x10sourceVolumeName\x12\x12\n" +
	"\x04zone\x18\x03 \x01(\tR\x04zone\"\xca\x01\n" +
	"\x16CreateSnapshotResponse\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12 \n" +
	"\fready_to_use\x18\x02 \x01(\bR\n" +
	"readyToUse\x12,\n" +
	"\x12restore_size_bytes\x18\x03 \x01(\x03R\x10restoreSizeBytes\x12?\n" +
	"\rcreation_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\"8\n" +
	"\x15DeleteSnapshotRequest\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\"\x18\n" +
	"\x16DeleteSnapshotResponse\"\xad\x01\n" +
	"\x14ListSnapshotsRequest\x12,\n" +
	"\x12source_volume_name\x18\x01 \x01(\tR\x10sourceVolumeName\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\x12\x1f\n" +
	"\vmax_entries\x18\x03 \x01(\x05R\n" +
	"maxEntries\x12%\n" +
	"\x0estarting_token\x18\x04 \x01(\tR\rstartingToken\"\xea\x02\n" +
	"\x15ListSnapshotsResponse\x12L\n" +
	"\aentries\x18\x01 \x03(\v22.proxmox.csi.volume.v1.ListSnapshotsResponse.EntryR\aentries\x12\x1d\n" +
	"\n" +
	"next_token\x18\x02 \x01(\tR\tnextToken\x1a\xe3\x01\n" +
	"\x05Entry\x12\x1f\n" +
	"\vsnapshot_id\x18\x01 \x01(\tR\n" +
	"snapshotId\x12(\n" +
	"\x10source_volume_id\x18\x02 \x01(\tR\x0esourceVolumeId\x12 \n" +
	"\fready_to_use\x18\x03 \x01(\bR\n" +
	"readyToUse\x12,\n" +
	"\x12restore_size_bytes\x18\x04 \x01(\x03R\x10restoreSizeBytes\x12?\n" +
	"\rcreation_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\fcreationTime\"D\n" +
	"\x14WatchCapacityRequest\x12\x18\n" +
	"\astorage\x18\x01 \x01(\tR\astorage\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\"\xa7\x01\n" +
	"\x15WatchCapacityResponse\x12\x18\n" +
	"\astorage\x18\x01 \x01(\tR\astorage\x12\x12\n" +
	"\x04zone\x18\x02 \x01(\tR\x04zone\x12'\n" +
	"\x0favailable_bytes\x18\x03 \x01(\x03R\x0eavailableBytes\x12\x1f\n" +
	"\vtotal_bytes\x18\x04 \x01(\x03R\n" +
	"totalBytes\x12\x16\n" +
	"\x06shared\x18\x05 \x01(\bR\x06shared2\xbd\b\n" +
	"\rVolumeService\x12g\n" +
	"\fCreateVolume\x12*.proxmox.csi.volume.v1.CreateVolumeRequest\x1a+.proxmox.csi.volume.v1.CreateVolumeResponse\x12g\n" +
	"\fDeleteVolume\x12*.proxmox.csi.volume.v1.DeleteVolumeRequest\x1a+.proxmox.csi.volume.v1.DeleteVolumeResponse\x12g\n" +
	"\fExpandVolume\x12*.proxmox.csi.volume.v1.ExpandVolumeRequest\x1a+.proxmox.csi.volume.v1.ExpandVolumeResponse\x12g\n" +
	"\fModifyVolume\x12*.proxmox.csi.volume.v1.ModifyVolumeRequest\x1a+.proxmox.csi.volume.v1.ModifyVolumeResponse\x12g\n" +
	"\fAttachVolume\x12*.proxmox.csi.volume.v1.AttachVolumeRequest\x1a+.proxmox.csi.volume.v1.AttachVolumeResponse\x12g\n" +
	"\fDetachVolume\x12*.proxmox.csi.volume.v1.DetachVolumeRequest\x1a+.proxmox.csi.volume.v1.DetachVolumeResponse\x12m\n" +
	"\x0eCreateSnapshot\x12,.proxmox.csi.volume.v1.CreateSnapshotRequest\x1a-.proxmox.csi.volume.v1.CreateSnapshotResponse\x12m\n" +
	"\x0eDeleteSnapshot\x12,.proxmox.csi.volume.v1.DeleteSnapshotRequest\x1a-.proxmox.csi.volume.v1.DeleteSnapshotResponse\x12j\n" +
	"\rListSnapshots\x12+.proxmox.csi.volume.v1.ListSnapshotsRequest\x1a,.proxmox.csi.volume.v1.ListSnapshotsResponse\x12l\n" +
	"\rWatchCapacity\x12+.proxmox.csi.volume.v1.WatchCapacityRequest\x1a,.proxmox.csi.volume.v1.WatchCapacityResponse0\x01BIZGgithub.com/sergelogvinov/proxmox-csi-plugin/pkg/apis/volume/v1;volumev1b\x06proto3"

var (
	file_volume_v1_volume_proto_rawDescOnce sync.Once
	file_volume_v1_volume_proto_rawDescData []byte
)

func file_volume_v1_volume_proto_rawDescGZIP() []byte {
	file_volume_v1_volume_proto_rawDescOnce.Do(func() {
		file_volume_v1_volume_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_volume_v1_volume_proto_rawDesc), len(file_volume_v1_volume_proto_rawDesc)))
	})
	return file_volume_v1_volume_proto_rawDescData
}

var file_volume_v1_volume_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_volume_v1_volume_proto_goTypes = []any{
	(*ClaimRef)(nil),                    // 0: proxmox.csi.volume.v1.ClaimRef
	(*VolumeSource)(nil),                // 1: proxmox.csi.volume.v1.VolumeSource
	(*TopologyRequirement)(nil),         // 2: proxmox.csi.volume.v1.TopologyRequirement
	(*CreateVolumeRequest)(nil),         // 3: proxmox.csi.volume.v1.CreateVolumeRequest
	(*CreateVolumeResponse)(nil),        // 4: proxmox.csi.volume.v1.CreateVolumeResponse
	(*DeleteVolumeRequest)(nil),         // 5: proxmox.csi.volume.v1.DeleteVolumeRequest
	(*DeleteVolumeResponse)(nil),        // 6: proxmox.csi.volume.v1.DeleteVolumeResponse
	(*ExpandVolumeRequest)(nil),         // 7: proxmox.csi.volume.v1.ExpandVolumeRequest
	(*ExpandVolumeResponse)(nil),        // 8: proxmox.csi.volume.v1.ExpandVolumeResponse
	(*ModifyVolumeRequest)(nil),         // 9: proxmox.csi.volume.v1.ModifyVolumeRequest
	(*ModifyVolumeResponse)(nil),        // 10: proxmox.csi.volume.v1.ModifyVolumeResponse
	(*AttachVolumeRequest)(nil),         // 11: proxmox.csi.volume.v1.AttachVolumeRequest
	(*AttachVolumeResponse)(nil),        // 12: proxmox.csi.volume.v1.AttachVolumeResponse
	(*DetachVolumeRequest)(nil),         // 13: proxmox.csi.volume.v1.DetachVolumeRequest
	(*DetachVolumeResponse)(nil),        // 14: proxmox.csi.volume.v1.DetachVolumeResponse
	(*CreateSnapshotRequest)(nil),       // 15: proxmox.csi.volume.v1.CreateSnapshotRequest
	(*CreateSnapshotResponse)(nil),      // 16: proxmox.csi.volume.v1.CreateSnapshotResponse
	(*DeleteSnapshotRequest)(nil),       // 17: proxmox.csi.volume.v1.DeleteSnapshotRequest
	(*DeleteSnapshotResponse)(nil),      // 18: proxmox.csi.volume.v1.DeleteSnapshotResponse
	(*ListSnapshotsRequest)(nil),        // 19: proxmox.csi.volume.v1.ListSnapshotsRequest
	(*ListSnapshotsResponse)(nil),       // 20: proxmox.csi.volume.v1.ListSnapshotsResponse
	(*WatchCapacityRequest)(nil),        // 21: proxmox.csi.volume.v1.WatchCapacityRequest
	(*WatchCapacityResponse)(nil),       // 22: proxmox.csi.volume.v1.WatchCapacityResponse
	nil,                                 // 23: proxmox.csi.volume.v1.CreateVolumeRequest.ParametersEntry
	nil,                                 // 24: proxmox.csi.volume.v1.CreateVolumeRequest.MutableParametersEntry
	nil,                                 // 25: proxmox.csi.volume.v1.CreateVolumeResponse.VolumeContextEntry
	nil,                                 // 26: proxmox.csi.volume.v1.ModifyVolumeRequest.MutableParametersEntry
	nil,                                 // 27: proxmox.csi.volume.v1.AttachVolumeRequest.MutableParametersEntry
	(*ListSnapshotsResponse_Entry)(nil), // 28: proxmox.csi.volume.v1.ListSnapshotsResponse.Entry
	(*timestamppb.Timestamp)(nil),       // 29: google.protobuf.Timestamp
}
var file_volume_v1_volume_proto_depIdxs = []int32{
	0,  // 0: proxmox.csi.volume.v1.CreateVolumeRequest.claim_ref:type_name -> proxmox.csi.volume.v1.ClaimRef
	23, // 1: proxmox.csi.volume.v1.CreateVolumeRequest.parameters:type_name -> proxmox.csi.volume.v1.CreateVolumeRequest.ParametersEntry
	24, // 2: proxmox.csi.volume.v1.CreateVolumeRequest.mutable_parameters:type_name -> proxmox.csi.volume.v1.CreateVolumeRequest.MutableParametersEntry
	1,  // 3: proxmox.csi.volume.v1.CreateVolumeRequest.source:type_name -> proxmox.csi.volume.v1.VolumeSource
	2,  // 4: proxmox.csi.volume.v1.CreateVolumeRequest.topology_requirement:type_name -> proxmox.csi.volume.v1.TopologyRequirement
	25, // 5: proxmox.csi.volume.v1.CreateVolumeResponse.volume_context:type_name -> proxmox.csi.volume.v1.CreateVolumeResponse.VolumeContextEntry
	26, // 6: proxmox.csi.volume.v1.ModifyVolumeRequest.mutable_parameters:type_name -> proxmox.csi.volume.v1.ModifyVolumeRequest.MutableParametersEntry
	27, // 7: proxmox.csi.volume.v1.AttachVolumeRequest.mutable_parameters:type_name -> proxmox.csi.volume.v1.AttachVolumeRequest.MutableParametersEntry
	29, // 8: proxmox.csi.volume.v1.CreateSnapshotResponse.creation_time:type_name -> google.protobuf.Timestamp
	28, // 9: proxmox.csi.volume.v1.ListSnapshotsResponse.entries:type_name -> proxmox.csi.volume.v1.ListSnapshotsResponse.Entry
	29, // 10: proxmox.csi.volume.v1.ListSnapshotsResponse.Entry.creation_time:type_name -> google.protobuf.Timestamp
	3,  // 11: proxmox.csi.volume.v1.VolumeService.CreateVolume:input_type -> proxmox.csi.volume.v1.CreateVolumeRequest
	5,  // 12: proxmox.csi.volume.v1.VolumeService.DeleteVolume:input_type -> proxmox.csi.volume.v1.DeleteVolumeRequest
	7,  // 13: proxmox.csi.volume.v1.VolumeService.ExpandVolume:input_type -> proxmox.csi.volume.v1.ExpandVolumeRequest
	9,  // 14: proxmox.csi.volume.v1.VolumeService.ModifyVolume:input_type -> proxmox.csi.volume.v1.ModifyVolumeRequest
	11, // 15: proxmox.csi.volume.v1.VolumeService.AttachVolume:input_type -> proxmox.csi.volume.v1.AttachVolumeRequest
	13, // 16: proxmox.csi.volume.v1.VolumeService.DetachVolume:input_type -> proxmox.csi.volume.v1.DetachVolumeRequest
	15, // 17: proxmox.csi.volume.v1.VolumeService.CreateSnapshot:input_type -> proxmox.csi.volume.v1.CreateSnapshotRequest
	17, // 18: proxmox.csi.volume.v1.VolumeService.DeleteSnapshot:input_type -> proxmox.csi.volume.v1.DeleteSnapshotRequest
	19, // 19: proxmox.csi.volume.v1.VolumeService.ListSnapshots:input_type -> proxmox.csi.volume.v1.ListSnapshotsRequest
	21, // 20: proxmox.csi.volume.v1.VolumeService.WatchCapacity:input_type -> proxmox.csi.volume.v1.WatchCapacityRequest
	4,  // 21: proxmox.csi.volume.v1.VolumeService.CreateVolume:output_type -> proxmox.csi.volume.v1.CreateVolumeResponse
	6,  // 22: proxmox.csi.volume.v1.VolumeService.DeleteVolume:output_type -> proxmox.csi.volume.v1.DeleteVolumeResponse
	8,  // 23: proxmox.csi.volume.v1.VolumeService.ExpandVolume:output_type -> proxmox.csi.volume.v1.ExpandVolumeResponse
	10, // 24: proxmox.csi.volume.v1.VolumeService.ModifyVolume:output_type -> proxmox.csi.volume.v1.ModifyVolumeResponse
	12, // 25: proxmox.csi.volume.v1.VolumeService.AttachVolume:output_type -> proxmox.csi.volume.v1.AttachVolumeResponse
	14, // 26: proxmox.csi.volume.v1.VolumeService.DetachVolume:output_type -> proxmox.csi.volume.v1.DetachVolumeResponse
	16, // 27: proxmox.csi.volume.v1.VolumeService.CreateSnapshot:output_type -> proxmox.csi.volume.v1.CreateSnapshotResponse
	18, // 28: proxmox.csi.volume.v1.VolumeService.DeleteSnapshot:output_type -> proxmox.csi.volume.v1.DeleteSnapshotResponse
	20, // 29: proxmox.csi.volume.v1.VolumeService.ListSnapshots:output_type -> proxmox.csi.volume.v1.ListSnapshotsResponse
	22, // 30: proxmox.csi.volume.v1.VolumeService.WatchCapacity:output_type -> proxmox.csi.volume.v1.WatchCapacityResponse
	21, // [21:31] is the sub-list for method output_type
	11, // [11:21] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_volume_v1_volume_proto_init() }
func file_volume_v1_volume_proto_init() {
	if File_volume_v1_volume_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_volume_v1_volume_proto_rawDesc), len(file_volume_v1_volume_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_volume_v1_volume_proto_goTypes,
		DependencyIndexes: file_volume_v1_volume_proto_depIdxs,
		MessageInfos:      file_volume_v1_volume_proto_msgTypes,
	}.Build()
	File_volume_v1_volume_proto = out.File
	file_volume_v1_volume_proto_goTypes = nil
	file_volume_v1_volume_proto_depIdxs = nil
}
