// Copyright 2023 The Kubernetes Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// The volume API served by the operator binary (ADR 6).
//
// Every request is authenticated by a Keycloak bearer token whose azp resolves
// to exactly one TenantCluster and therefore one namespace. No field in this
// proto carries a namespace, tenant identity or owner: those are derived from
// the bearer token by the server and never accepted from the wire. This is the
// reason a compromised tenant cannot name another tenant's namespace, and it is
// load-bearing -- see volume-control-plane.md, "Authorization: four layers".

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: volume/v1/volume.proto

package volumev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VolumeService_CreateVolume_FullMethodName   = "/proxmox.csi.volume.v1.VolumeService/CreateVolume"
	VolumeService_DeleteVolume_FullMethodName   = "/proxmox.csi.volume.v1.VolumeService/DeleteVolume"
	VolumeService_ExpandVolume_FullMethodName   = "/proxmox.csi.volume.v1.VolumeService/ExpandVolume"
	VolumeService_ModifyVolume_FullMethodName   = "/proxmox.csi.volume.v1.VolumeService/ModifyVolume"
	VolumeService_AttachVolume_FullMethodName   = "/proxmox.csi.volume.v1.VolumeService/AttachVolume"
	VolumeService_DetachVolume_FullMethodName   = "/proxmox.csi.volume.v1.VolumeService/DetachVolume"
	VolumeService_CreateSnapshot_FullMethodName = "/proxmox.csi.volume.v1.VolumeService/CreateSnapshot"
	VolumeService_DeleteSnapshot_FullMethodName = "/proxmox.csi.volume.v1.VolumeService/DeleteSnapshot"
	VolumeService_ListSnapshots_FullMethodName  = "/proxmox.csi.volume.v1.VolumeService/ListSnapshots"
	VolumeService_WatchCapacity_FullMethodName  = "/proxmox.csi.volume.v1.VolumeService/WatchCapacity"
)

// VolumeServiceClient is the client API for VolumeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VolumeService is the tenant-facing volume API.
//
// Each method maps one-to-one onto the CRD the operator reconciles: the server
// writes the tenant's intent as a custom resource and returns once the
// reconciler has acted on it or refused it. The proto lives at
// api/volume/v1 and TLS terminates at Envoy Gateway with h2c to the pod.
type VolumeServiceClient interface {
	// CreateVolume provisions a new Proxmox disk or clones an existing one.
	CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	// DeleteVolume removes a provisioned disk.
	DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error)
	// ExpandVolume grows an existing disk. Shrinking is rejected.
	ExpandVolume(ctx context.Context, in *ExpandVolumeRequest, opts ...grpc.CallOption) (*ExpandVolumeResponse, error)
	// ModifyVolume patches the mutable parameters (IO throttle, cache, etc.)
	// on an attached volume.
	ModifyVolume(ctx context.Context, in *ModifyVolumeRequest, opts ...grpc.CallOption) (*ModifyVolumeResponse, error)
	// AttachVolume attaches a disk to a VM, returning the device path and LUN
	// the node plugin needs.
	AttachVolume(ctx context.Context, in *AttachVolumeRequest, opts ...grpc.CallOption) (*AttachVolumeResponse, error)
	// DetachVolume detaches a disk from a VM.
	DetachVolume(ctx context.Context, in *DetachVolumeRequest, opts ...grpc.CallOption) (*DetachVolumeResponse, error)
	// CreateSnapshot creates a point-in-time copy of a volume.
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	// DeleteSnapshot removes a snapshot disk.
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	// ListSnapshots returns the tenant's own snapshots.
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// WatchCapacity streams storage capacity updates filtered to the tenant's
	// allowed storages. The tenant backend serves GetCapacity from this stream's
	// informer cache.
	WatchCapacity(ctx context.Context, in *WatchCapacityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchCapacityResponse], error)
}

type volumeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVolumeServiceClient(cc grpc.ClientConnInterface) VolumeServiceClient {
	return &volumeServiceClient{cc}
}

func (c *volumeServiceClient) CreateVolume(ctx context.Context, in *CreateVolumeRequest, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeService_CreateVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) DeleteVolume(ctx context.Context, in *DeleteVolumeRequest, opts ...grpc.CallOption) (*DeleteVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeService_DeleteVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) ExpandVolume(ctx context.Context, in *ExpandVolumeRequest, opts ...grpc.CallOption) (*ExpandVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpandVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeService_ExpandVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) ModifyVolume(ctx context.Context, in *ModifyVolumeRequest, opts ...grpc.CallOption) (*ModifyVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ModifyVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeService_ModifyVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) AttachVolume(ctx context.Context, in *AttachVolumeRequest, opts ...grpc.CallOption) (*AttachVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AttachVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeService_AttachVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) DetachVolume(ctx context.Context, in *DetachVolumeRequest, opts ...grpc.CallOption) (*DetachVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DetachVolumeResponse)
	err := c.cc.Invoke(ctx, VolumeService_DetachVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, VolumeService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, VolumeService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, VolumeService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *volumeServiceClient) WatchCapacity(ctx context.Context, in *WatchCapacityRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WatchCapacityResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VolumeService_ServiceDesc.Streams[0], VolumeService_WatchCapacity_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchCapacityRequest, WatchCapacityResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolumeService_WatchCapacityClient = grpc.ServerStreamingClient[WatchCapacityResponse]

// VolumeServiceServer is the server API for VolumeService service.
// All implementations must embed UnimplementedVolumeServiceServer
// for forward compatibility.
//
// VolumeService is the tenant-facing volume API.
//
// Each method maps one-to-one onto the CRD the operator reconciles: the server
// writes the tenant's intent as a custom resource and returns once the
// reconciler has acted on it or refused it. The proto lives at
// api/volume/v1 and TLS terminates at Envoy Gateway with h2c to the pod.
type VolumeServiceServer interface {
	// CreateVolume provisions a new Proxmox disk or clones an existing one.
	CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error)
	// DeleteVolume removes a provisioned disk.
	DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error)
	// ExpandVolume grows an existing disk. Shrinking is rejected.
	ExpandVolume(context.Context, *ExpandVolumeRequest) (*ExpandVolumeResponse, error)
	// ModifyVolume patches the mutable parameters (IO throttle, cache, etc.)
	// on an attached volume.
	ModifyVolume(context.Context, *ModifyVolumeRequest) (*ModifyVolumeResponse, error)
	// AttachVolume attaches a disk to a VM, returning the device path and LUN
	// the node plugin needs.
	AttachVolume(context.Context, *AttachVolumeRequest) (*AttachVolumeResponse, error)
	// DetachVolume detaches a disk from a VM.
	DetachVolume(context.Context, *DetachVolumeRequest) (*DetachVolumeResponse, error)
	// CreateSnapshot creates a point-in-time copy of a volume.
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	// DeleteSnapshot removes a snapshot disk.
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	// ListSnapshots returns the tenant's own snapshots.
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// WatchCapacity streams storage capacity updates filtered to the tenant's
	// allowed storages. The tenant backend serves GetCapacity from this stream's
	// informer cache.
	WatchCapacity(*WatchCapacityRequest, grpc.ServerStreamingServer[WatchCapacityResponse]) error
	mustEmbedUnimplementedVolumeServiceServer()
}

// UnimplementedVolumeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVolumeServiceServer struct{}

func (UnimplementedVolumeServiceServer) CreateVolume(context.Context, *CreateVolumeRequest) (*CreateVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVolume not implemented")
}
func (UnimplementedVolumeServiceServer) DeleteVolume(context.Context, *DeleteVolumeRequest) (*DeleteVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteVolume not implemented")
}
func (UnimplementedVolumeServiceServer) ExpandVolume(context.Context, *ExpandVolumeRequest) (*ExpandVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExpandVolume not implemented")
}
func (UnimplementedVolumeServiceServer) ModifyVolume(context.Context, *ModifyVolumeRequest) (*ModifyVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ModifyVolume not implemented")
}
func (UnimplementedVolumeServiceServer) AttachVolume(context.Context, *AttachVolumeRequest) (*AttachVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AttachVolume not implemented")
}
func (UnimplementedVolumeServiceServer) DetachVolume(context.Context, *DetachVolumeRequest) (*DetachVolumeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DetachVolume not implemented")
}
func (UnimplementedVolumeServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedVolumeServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedVolumeServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedVolumeServiceServer) WatchCapacity(*WatchCapacityRequest, grpc.ServerStreamingServer[WatchCapacityResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchCapacity not implemented")
}
func (UnimplementedVolumeServiceServer) mustEmbedUnimplementedVolumeServiceServer() {}
func (UnimplementedVolumeServiceServer) testEmbeddedByValue()                       {}

// UnsafeVolumeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VolumeServiceServer will
// result in compilation errors.
type UnsafeVolumeServiceServer interface {
	mustEmbedUnimplementedVolumeServiceServer()
}

func RegisterVolumeServiceServer(s grpc.ServiceRegistrar, srv VolumeServiceServer) {
	// If the following call panics, it indicates UnimplementedVolumeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VolumeService_ServiceDesc, srv)
}

func _VolumeService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_CreateVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).CreateVolume(ctx, req.(*CreateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_DeleteVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).DeleteVolume(ctx, req.(*DeleteVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_ExpandVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).ExpandVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_ExpandVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).ExpandVolume(ctx, req.(*ExpandVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_ModifyVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).ModifyVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_ModifyVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).ModifyVolume(ctx, req.(*ModifyVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_AttachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AttachVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).AttachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_AttachVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).AttachVolume(ctx, req.(*AttachVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_DetachVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DetachVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).DetachVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_DetachVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).DetachVolume(ctx, req.(*DetachVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VolumeServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VolumeService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VolumeServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VolumeService_WatchCapacity_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchCapacityRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VolumeServiceServer).WatchCapacity(m, &grpc.GenericServerStream[WatchCapacityRequest, WatchCapacityResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VolumeService_WatchCapacityServer = grpc.ServerStreamingServer[WatchCapacityResponse]

// VolumeService_ServiceDesc is the grpc.ServiceDesc for VolumeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VolumeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proxmox.csi.volume.v1.VolumeService",
	HandlerType: (*VolumeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateVolume",
			Handler:    _VolumeService_CreateVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _VolumeService_DeleteVolume_Handler,
		},
		{
			MethodName: "ExpandVolume",
			Handler:    _VolumeService_ExpandVolume_Handler,
		},
		{
			MethodName: "ModifyVolume",
			Handler:    _VolumeService_ModifyVolume_Handler,
		},
		{
			MethodName: "AttachVolume",
			Handler:    _VolumeService_AttachVolume_Handler,
		},
		{
			MethodName: "DetachVolume",
			Handler:    _VolumeService_DetachVolume_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _VolumeService_CreateSnapshot_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _VolumeService_DeleteSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _VolumeService_ListSnapshots_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchCapacity",
			Handler:       _VolumeService_WatchCapacity_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "volume/v1/volume.proto",
}
