{{- if and .Values.migrator.enabled (not .Values.migrator.existingConfigSecret) }}
{{- if eq (len .Values.migrator.config.clusters) 0 }}
{{- fail "migrator.config.clusters (with root username/password) or migrator.existingConfigSecret is required when migrator.enabled is true" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxmox-csi-plugin.fullname" . }}-migrator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "proxmox-csi-plugin.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.migrator.config | b64enc | quote }}
{{- end }}
